### ISSUE TITLE
Can this library be used on raspberry pi 3 B+?

### ISSUE THREAD

**Issue by aqib11** [iitzco/faced#2]

**Comment by iitzco** [comment]
Hi @aqib11 !

I haven't tested it on a Raspberry PI, but it should work. You should figure out how to run tensorflow and opencv on the device.

#### For tensorflow:
Note that [tensorflow > 1.9 officially supports Raspberry Pi](https://medium.com/tensorflow/tensorflow-1-9-officially-supports-the-raspberry-pi-b91669b0aa0).

#### For opencv:
You can follow [this tutorial to install opencv](https://www.pyimagesearch.com/2016/04/18/install-guide-raspberry-pi-3-raspbian-jessie-opencv-3/) on the Raspberry Pi.

**Comment by iitzco** [comment]
I will close this issue for now...feel free to reopen it if you can't make it work.
