### ISSUE TITLE
GPU requirements

### ISSUE THREAD

**Issue by LumaRay** [iitzco/faced#36]
Hello!
Thanks for the project, it works for me.
But I have strange results with my GTX 1080 Ti. 
For some reason when I install Tensorflow with CUDA support and check GPU usage in MSI Afterburner, it shows that 10.6 of 11 Gb video memory is used. And this is not a training mode - I just use these already trained models.
Does that mean that it really needs so much video memory or this program just fills all the memory a video card provides?
Will this work on some GT 730 4G GPU as well? Or it will be not enough video memory?
How much video memory does the module require?
Thanks!

**Comment by Rohansjamadagni** [comment]
That's just tensorflow allocating memory, actual usage will be <2gb

**Comment by LumaRay** [comment]
Thanks!
